### ISSUE TITLE
Request timeout

### ISSUE THREAD

**Issue by cwdcwd** [cloudspokes/GLIB-mock#22]
The request() call, when posting into the TC API, occasionally times out. Seeing upwards of 30s in some events

**Comment by cwdcwd** [comment]
Failed to create challenge
Status code: 503
Response body:
```
"<!DOCTYPE html>\n\t<html>\n\t  <head>\n\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n\t\t<meta charset=\"utf-8\">\n\t\t<title>Application Error</title>\n\t\t<style media=\"screen\">\n\t\t  html,body,iframe {\n\t\t\tmargin: 0;\n\t\t\tpadding: 0;\n\t\t  }\n\t\t  html,body {\n\t\t\theight: 100%;\n\t\t\toverflow: hidden;\n\t\t  }\n\t\t  iframe {\n\t\t\twidth: 100%;\n\t\t\theight: 100%;\n\t\t\tborder: 0;\n\t\t  }\n\t\t</style>\n\t  </head>\n\t  <body>\n\t\t<iframe src=\"//www.herokucdn.com/error-pages/application-error.html\"></iframe>\n\t  </body>\n\t</html>"
```

**Comment by jmgasper** [comment]
Hmmm...  OK.  I'll take a look.  Was this done through the mock directly or by configuring the plugin to point at the mock?

**Comment by jmgasper** [comment]
Also, which Heroku instance is this on?  Do I have access to take a look at the logs?

**Comment by cwdcwd** [comment]
hitting prod

**Comment by cwdcwd** [comment]
yes you should

**Comment by jmgasper** [comment]
👍

**Comment by cwdcwd** [comment]
oh prod might need to be reconfig'd

**Comment by cwdcwd** [comment]
the `APIURL_BASE`, `APIURL_CHALLENGE`,  and `APIURL_OAUTHACCESS` all might need updating

**Comment by cwdcwd** [comment]
Failed to create challenge
Status code: 404
Response body:
```
"<!DOCTYPE html>\n<html>\n  <head>\n    <title></title>\n    <link rel='stylesheet' href='/stylesheets/style.css' />\n  </head>\n  <body>\n    <h1>Not Found</h1>\n<h2>404</h2>\n<pre>Error: Not Found\n    at /app/app.js:30:15\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/app/node_modules/express/lib/router/index.js:312:13)\n    at /app/node_modules/express/lib/router/index.js:280:7\n    at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)\n    at next (/app/node_modules/express/lib/router/index.js:271:10)\n    at /app/node_modules/express/lib/router/index.js:618:15\n    at next (/app/node_modules/express/lib/router/index.js:256:14)\n    at Function.handle (/app/node_modules/express/lib/router/index.js:176:3)\n    at router (/app/node_modules/express/lib/router/index.js:46:12)</pre>\n\n  </body>\n</html>\n"
```

**Comment by cwdcwd** [comment]
Failed to create challenge
Status code: 404
Response body:
```
"<!DOCTYPE html>\n<html>\n  <head>\n    <title></title>\n    <link rel='stylesheet' href='/stylesheets/style.css' />\n  </head>\n  <body>\n    <h1>Not Found</h1>\n<h2>404</h2>\n<pre>Error: Not Found\n    at /app/app.js:30:15\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/app/node_modules/express/lib/router/index.js:312:13)\n    at /app/node_modules/express/lib/router/index.js:280:7\n    at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)\n    at next (/app/node_modules/express/lib/router/index.js:271:10)\n    at /app/node_modules/express/lib/router/index.js:618:15\n    at next (/app/node_modules/express/lib/router/index.js:256:14)\n    at Function.handle (/app/node_modules/express/lib/router/index.js:176:3)\n    at router (/app/node_modules/express/lib/router/index.js:46:12)</pre>\n\n  </body>\n</html>\n"
```
